### ISSUE TITLE
Posibility of re-publishing latest version of OpenTM2 (+ plugins)

### ISSUE THREAD

**Issue by rampa3** [OpenTM2/installer#1]
Hello,

I know the project is dead, as is stated in the source code repository readme, but still I would like to ask if it would be possible to re-publish anywhere the latest working version of OpenTM2 and possibly at least some plugins, provided anyone has those files archived. I have a translation project I started in OpenTM2 around year 2020, when the websites were still up, but I had to reinstall my computer lately and now I can't find any archive of anything OpenTM2 anywhere, except for very old version on SourceForge and version 1.3.0 on some random download site. Is there any chance of the latest release being recovered from anywhere, or I will have to re-construct the project manually in different CAT tool?

Thank you in advance for any answers!

**Comment by marcmittag** [comment]
I probably still have the installers of the 2 latest versions, yet I'm traveling at the moment, so only will be able to look for it at the end of the week/start of next week.
If so, I will upload them here.

**Comment by marcmittag** [comment]
Hi there,
I just provided the 2 latest versions for download at https://www.translate5.net/.
Please find the links in the readme of this repo.
best
Marc

**Comment by rampa3** [comment]
> Hi there, I just provided the 2 latest versions for download at https://www.translate5.net/. Please find the links in the readme of this repo. best Marc

Thank you! Now I can continue where I left off with my translations.
